### ISSUE TITLE
Reference: window is not defined in local development environment

### ISSUE THREAD

**Issue by nsvrana** [hashintel/hash#4196]
### Describe the bug

When attempting to run hash locally on a fresh, otherwise empty Debian 12 installation, I receive the following error when I visit the webserver from any browser on the main branch with local code from the latest commit (932ecc4). The external services are running properly, codegen ran completely, and I've tried a "yarn fix" as well. I recognize things are under active development and self-hosting isn't a focus now, but I thought I would share in case it helps fix in the future.

```
~/hash# yarn dev
yarn run v1.22.22
$ turbo dev --log-order stream --filter '@apps/hash-api' --filter '@apps/hash-search-loader' --filter '@apps/hash-realtime' --filter '@apps/hash-frontend' --
• Packages in scope: @apps/hash-api, @apps/hash-frontend, @apps/hash-realtime, @apps/hash-search-loader
• Running dev in 4 packages
• Remote caching disabled
@apps/hash-frontend:dev: cache miss, executing 2b11bb849fe140c5
@apps/hash-api:dev: cache miss, executing 49e8fde7c4d198b5
@apps/hash-realtime:dev: cache miss, executing 26c3b33f51b248a1
$ yarn clear-redis && NODE_ENV=development NODE_OPTIONS=--max-old-space-size=2048 tsx watch --clear-screen=false ./src/index.ts
$ NODE_ENV=development NODE_OPTIONS=--max-old-space-size=2048 tsx watch --clear-screen=false ./src/index.ts
$ next dev
$ tsx ./src/scripts/clear-redis.ts
@apps/hash-api:dev: 5:14:13 PM [tsx] rerunning
@apps/hash-realtime:dev: (node:188884) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
@apps/hash-realtime:dev: --import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///root/hash/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
@apps/hash-realtime:dev: (Use `node --trace-warnings ...` to show where the warning was created)
@apps/hash-realtime:dev: (node:188884) UnsupportedWarning: `globalPreload` has been removed; use `initialize` instead.
@apps/hash-realtime:dev: (Use `node --trace-warnings ...` to show where the warning was created)
@apps/hash-api:dev: (node:188890) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
@apps/hash-api:dev: --import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///root/hash/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
@apps/hash-api:dev: (Use `node --trace-warnings ...` to show where the warning was created)
@apps/hash-api:dev: (node:188890) UnsupportedWarning: `globalPreload` has been removed; use `initialize` instead.
@apps/hash-api:dev: (Use `node --trace-warnings ...` to show where the warning was created)
@apps/hash-realtime:dev: info: Redis data cleared {"service":"clear-redis-queues"}
@apps/hash-search-loader:dev: cache hit, replaying logs 2c2db096576b01e4
$ echo 'Opensearch currently disabled'
@apps/hash-search-loader:dev: Opensearch currently disabled
@apps/hash-frontend:dev:   ▲ Next.js 13.5.5
@apps/hash-frontend:dev:   - Local:        http://localhost:3000
@apps/hash-frontend:dev:   - Experiments (use at your own risk):
@apps/hash-frontend:dev:      · outputFileTracingExcludes
@apps/hash-frontend:dev: 
@apps/hash-frontend:dev:  ✓ Ready in 1137ms
@apps/hash-api:dev: (node:188890) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
@apps/hash-api:dev: info: Type System initialized {"service":"api"}
@apps/hash-api:dev: info: Registered OpenTelemetry trace exporter at endpoint http://localhost:4317 {"service":"api"}
@apps/hash-api:dev: info: Seeded User available, email = "admin@example.com". {"service":"api"}
@apps/hash-api:dev: info: Seeded User available, email = "alice@example.com". {"service":"api"}
@apps/hash-api:dev: info: Seeded User available, email = "bob@example.com". {"service":"api"}
@apps/hash-api:dev: info: Listening on port 5001 {"service":"api"}
@apps/hash-api:dev: info: GraphQL path: /graphql {"service":"api"}
@apps/hash-frontend:dev:  ✓ Compiled / in 2.7s (4254 modules)
@apps/hash-frontend:dev:  ⨯ ../node_modules/zrender/lib/core/env.js (66:49) @ window
@apps/hash-frontend:dev:  ⨯ ReferenceError: window is not defined
@apps/hash-frontend:dev:     at detect (webpack-internal:///../../node_modules/zrender/lib/core/env.js:66:50)
@apps/hash-frontend:dev:     at eval (webpack-internal:///../../node_modules/zrender/lib/core/env.js:41:5)
@apps/hash-frontend:dev:     at ../../node_modules/zrender/lib/core/env.js (/root/hash/apps/hash-frontend/.next/server/vendor-chunks/zrender.js:380:1)
@apps/hash-frontend:dev:     at __webpack_require__ (/root/hash/apps/hash-frontend/.next/server/webpack-runtime.js:33:42)
@apps/hash-frontend:dev:     at eval (webpack-internal:///../../node_modules/echarts/lib/model/Model.js:5:81)
@apps/hash-frontend:dev:     at ../../node_modules/echarts/lib/model/Model.js (/root/hash/apps/hash-frontend/.next/server/vendor-chunks/echarts.js:3980:1)
@apps/hash-frontend:dev:     at __webpack_require__ (/root/hash/apps/hash-frontend/.next/server/webpack-runtime.js:33:42)
@apps/hash-frontend:dev:     at eval (webpack-internal:///../../node_modules/echarts/lib/data/SeriesData.js:6:73)
@apps/hash-frontend:dev:     at ../../node_modules/echarts/lib/data/SeriesData.js (/root/hash/apps/hash-frontend/.next/server/vendor-chunks/echarts.js:3560:1)
@apps/hash-frontend:dev:     at __webpack_require__ (/root/hash/apps/hash-frontend/.next/server/webpack-runtime.js:33:42)
@apps/hash-frontend:dev:     at eval (webpack-internal:///../../node_modules/echarts/lib/chart/helper/createSeriesData.js:6:77)
@apps/hash-frontend:dev:     at ../../node_modules/echarts/lib/chart/helper/createSeriesData.js (/root/hash/apps/hash-frontend/.next/server/vendor-chunks/echarts.js:750:1)
@apps/hash-frontend:dev:     at __webpack_require__ (/root/hash/apps/hash-frontend/.next/server/webpack-runtime.js:33:42)
@apps/hash-frontend:dev:     at eval (webpack-internal:///../../node_modules/echarts/lib/chart/line/LineSeries.js:6:85)
@apps/hash-frontend:dev:     at ../../node_modules/echarts/lib/chart/line/LineSeries.js (/root/hash/apps/hash-frontend/.next/server/vendor-chunks/echarts.js:830:1) {
@apps/hash-frontend:dev:   page: '/'
@apps/hash-frontend:dev: }
@apps/hash-frontend:dev: null
```

**Comment by CiaranMn** [comment]
Thanks for the report @nsvrana, definitely helpful to have.

I can recreate your issue by using Node v21, and #4216 fixes it for me.

If you are not using Node 21 (`node -v`) then it may be something else, but it seems very likely that this is the problem.

Any other reports welcome, thanks again!
